[project]
name = "Charity-Matching-DAO"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Charity-Matching-DAO/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Charity-Matching-DAO]
path = "contracts/Charity-Matching-DAO.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
